"""add skills and job snapshot skills

Revision ID: 42df6bb80fa5
Revises: ab47d48a138d
Create Date: 2026-01-29 15:42:01.455204

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42df6bb80fa5"
down_revision: str | None = "ab47d48a138d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("normalized_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_name", name="uq_skills_normalized_name"),
    )
    op.create_table(
        "job_snapshot_skills",
        sa.Column("job_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_snapshot_id"], ["job_snapshots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_snapshot_id", "skill_id"),
    )
    op.create_index(
        "ix_job_snapshot_skills_job_snapshot_id",
        "job_snapshot_skills",
        ["job_snapshot_id"],
        unique=False,
    )
    op.create_index(
        "ix_job_snapshot_skills_skill_id", "job_snapshot_skills", ["skill_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_snapshot_skills_skill_id", table_name="job_snapshot_skills")
    op.drop_index("ix_job_snapshot_skills_job_snapshot_id", table_name="job_snapshot_skills")
    op.drop_table("job_snapshot_skills")
    op.drop_table("skills")
    # ### end Alembic commands ###
